// Exception Handling

exp="%10*2+5"
console.log('Exception Handling');
try{
    const result =eval(exp)
}
 
catch{
    console.log('Error in evaluation ');
  
}

finally{
    console.log('Task Completed');
}